version: '3'
services:
  lingxi-core:
    image: lingxi-core:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lingxi-core
    restart: always
    volumes:
      - ./volumes/app/storage:/app/api/storage
    environment:
      # 邮件服务器
      SMTP_SERVER: smtp.163.com
      SMTP_PORT: 465
      SENDER_EMAIL: '修改为自己的邮件地址'
      SMTP_PASSWORD: '修改为自己的邮件密码'
      # ollama地址
      OLLAMA_URL: http://127.0.0.1:9432
      # 云函数
      FUNCTION_CALL_URL: '云函数调用地址'
      # 私钥密码
      PRIVATE_KEY_PASSWORD: ysyhl9Day
      # 模式为API，代表启用API服务
      MODE: api
      SERVER_WORKER_AMOUNT: 4
      SERVER_THREAD_AMOUNT: 4
      # 数据库迁移配置
      MIGRATION_ENABLED: 'true'
      # JWT加密秘钥
      JWT_SECRET_KEY: Xzw3R1sIdCVALlOn2qHomN8jiHY6Eutx
      # CSRF校验开关
      WTF_CSRF_ENABLED: 'false'
      # SQLAlchemy数据库配置
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgres:5432/llmops?client_encoding=utf8
      SQLALCHEMY_POOL_SIZE: 30
      SQLALCHEMY_POOL_RECYCLE: 3600
      SQLALCHEMY_ECHO: 'true'
      # Redis缓存数据库配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ''
      REDIS_PASSWORD: 123456
      REDIS_DB: 0
      REDIS_USE_SSL: 'false'
      # Weaviate向量数据库配置
      WEAVIATE_HTTP_HOST: weaviate
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_HOST: weaviate
      WEAVIATE_GRPC_PORT: 50051
      WEAVIATE_API_KEY: ftBC9hKkjfdbdi0wW3T6kEtMh5BZFpGa1DF8
      # 腾讯云COS对象存储
      COS_SECRET_ID: '修改为自己的对象存储ID'
      COS_SECRET_KEY: '修改为自己的对象存储KEY'
      COS_REGION: '修改为自己的区域'
      COS_SCHEMA: https
      COS_BUCKET: '修改为自己的桶'
      COS_DOMAIN: ''
      # Celery异步队列任务配置
      CELERY_BROKER_DB: 1
      CELERY_RESULT_BACKEND_DB: 1
      CELERY_TASK_IGNORE_RESULT: 'true'
      CELERY_RESULT_EXPIRES: 3600
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: 'true'
      # Github OAuth应用秘钥
      GITHUB_CLIENT_ID: '修改为自己的Github OAuthID'
      GITHUB_CLIENT_SECRET: '修改为自己的密钥'
      GITHUB_REDIRECT_URI: https://www.bdjw-ai.cn/auth/authorize/github
      # LangSmith配置
      # LANGCHAIN_TRACING_V2: 'true'
      # LANGCHAIN_ENDPOINT:
      # LANGCHAIN_API_KEY:
      # LANGCHAIN_PROJECT:
      # HuggingFace配置
      TRANSFORMERS_OFFLINE: 0
      # 辅助Agent智能体应用id标识
      ASSISTANT_AGENT_ID: 6774fcef-b594-8008-b30c-a05b8190afe6
      # OpenAI服务提供者
      OPENAI_API_KEY: ''
      OPENAI_BASE_URL: ''
      # 百度千帆服务提供者
      qianfan_ak: ''
      qianfan_sk: ''
      # 月之暗面服务提供者
      MOONSHOT_API_KEY: ''
      MOONSHOT_API_BASE_URL: ''
      # 通义千问服务提供者
      DASHSCOPE_API_KEY: ''
      # 谷歌Serper搜索API秘钥
      SERPER_API_KEY: ''
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
      - weaviate
  celery:
    image: lingxi-core:1.0.0
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: lingxi-core
    restart: always
    volumes:
      - ./volumes/app/storage:/app/api/storage
    environment:
      # 邮件服务器
      SMTP_SERVER: smtp.163.com
      SMTP_PORT: 465
      SENDER_EMAIL: '修改为自己的邮件地址'
      SMTP_PASSWORD: '修改为自己的邮件密码'
      # ollama地址
      OLLAMA_URL: http://127.0.0.1:9432
      # 云函数
      FUNCTION_CALL_URL: '云函数调用地址'
      # 私钥密码
      PRIVATE_KEY_PASSWORD: ysyhl9Day
      # 模式为celery，代表启用Celery异步任务队列
      MODE: celery
      SERVER_WORKER_AMOUNT: 4
      SERVER_THREAD_AMOUNT: 4
      # 数据库迁移配置
      MIGRATION_ENABLED: 'true'
      # JWT加密秘钥
      JWT_SECRET_KEY: Xzw3R1sIdCVALlOn2qHomN8jiHY6Eutx
      # CSRF校验开关
      WTF_CSRF_ENABLED: 'false'
      # SQLAlchemy数据库配置
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@postgres:5432/llmops?client_encoding=utf8
      SQLALCHEMY_POOL_SIZE: 30
      SQLALCHEMY_POOL_RECYCLE: 3600
      SQLALCHEMY_ECHO: 'true'
      # Redis缓存数据库配置
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ''
      REDIS_PASSWORD: 123456
      REDIS_DB: 0
      REDIS_USE_SSL: 'false'
      # Weaviate向量数据库配置
      WEAVIATE_HTTP_HOST: weaviate
      WEAVIATE_HTTP_PORT: 8080
      WEAVIATE_GRPC_HOST: weaviate
      WEAVIATE_GRPC_PORT: 50051
      WEAVIATE_API_KEY: ftBC9hKkjfdbdi0wW3T6kEtMh5BZFpGa1DF8
      # 腾讯云COS对象存储
      COS_SECRET_ID: '修改为自己的对象存储ID'
      COS_SECRET_KEY: '修改为自己的对象存储KEY'
      COS_REGION: '修改为自己的区域'
      COS_SCHEMA: https
      COS_BUCKET: '修改为自己的桶'
      COS_DOMAIN: ''
      # Celery异步队列任务配置
      CELERY_BROKER_DB: 1
      CELERY_RESULT_BACKEND_DB: 1
      CELERY_TASK_IGNORE_RESULT: 'true'
      CELERY_RESULT_EXPIRES: 3600
      CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP: 'true'
      # Github OAuth应用秘钥
      GITHUB_CLIENT_ID: '修改为自己的Github OAuthID'
      GITHUB_CLIENT_SECRET: '修改为自己的密钥'
      GITHUB_REDIRECT_URI: https://www.bdjw-ai.cn/auth/authorize/github
      # LangSmith配置
      # LANGCHAIN_TRACING_V2: 'true'
      # LANGCHAIN_ENDPOINT:
      # LANGCHAIN_API_KEY:
      # LANGCHAIN_PROJECT:
      # HuggingFace配置
      TRANSFORMERS_OFFLINE: 0
      # 辅助Agent智能体应用id标识
      ASSISTANT_AGENT_ID: 6774fcef-b594-8008-b30c-a05b8190afe6
      # OpenAI服务提供者
      OPENAI_API_KEY: ''
      OPENAI_BASE_URL: ''
      # 百度千帆服务提供者
      qianfan_ak: ''
      qianfan_sk: ''
      # 月之暗面服务提供者
      MOONSHOT_API_KEY: ''
      MOONSHOT_API_BASE_URL: ''
      # 通义千问服务提供者
      DASHSCOPE_API_KEY: ''
      # 谷歌Serper搜索API秘钥
      SERPER_API_KEY: ''
    ports:
      - "5001:5001"
    depends_on:
      - postgres
      - redis
      - weaviate
  redis:
    image: redis:6-alpine
    restart: always
    container_name: redis
    volumes:
      - ./volumes/redis/data:/data
    # 启动redis服务时配置
    command: redis-server --requirepass 123456
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    ports:
      - "6379:6379"
  postgres:
    image: postgres:16.3-alpine
    restart: always
    container_name: postgres
    environment:
      # 配置默认的账户名、账户密码、默认数据库、数据存储的位置
      PGUSER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: llmops
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      # 将postgres数据挂载到本地./volumes/db/data上
      - ./volumes/db/data:/var/lib/postgresql/data/pgdata
      # 初始化脚本只有在空数据挂载的情况下才会触发执行(.sql/.sh等)，如果已经存在数据则不会执行
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # 每隔1s发起一个健康测试，最多重试30次
      test: [ "CMD", "pg_isready" ]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5432:5432"
  weaviate:
    image: semitechnologies/weaviate:1.28.4
    container_name: weaviate
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25  # 查询默认返回的数据条数
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'false'  # 需要授权才能和weaviate进行交互
      PERSISTENCE_DATA_PATH: /var/lib/weaviate  # weaviate数据存储路径
      DEFAULT_VECTORIZER_MODULE: 'none'  # 向量化模块设置为none
      CLUSTER_HOSTNAME: 'node1'  # 节点的主机名字
      AUTHENTICATION_APIKEY_ENABLED: 'true'  # 启动基于API秘钥的身份校验
      AUTHENTICATION_APIKEY_ALLOWED_KEYS: 'ftBC9hKkjfdbdi0wW3T6kEtMh5BZFpGa1DF8'  # 允许的API秘钥列表
      AUTHENTICATION_APIKEY_USERS: ''  # 基于秘钥的API身份列表
      AUTHORIZATION_ADMINLIST_ENABLED: 'true'  # 启动AdminList授权方案
      AUTHORIZATION_ADMINLIST_USERS: ''  # 使用AdminList方案时具有管理权限的用户
    volumes:
      - ./volumes/weaviate:/var/lib/weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
