"""empty message

Revision ID: 809b56b75327
Revises: 0cfa9aab24b1
Create Date: 2024-07-06 10:03:17.358966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '809b56b75327'
down_revision = '0cfa9aab24b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
