"""empty message

Revision ID: c50e05cb3459
Revises: a3a8aa8e1381
Create Date: 2025-07-31 09:43:48.259755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50e05cb3459'
down_revision = 'a3a8aa8e1381'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.add_column(sa.Column('en_name', sa.String(length=255), server_default=sa.text("''::character varying"), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app', schema=None) as batch_op:
        batch_op.drop_column('en_name')

    # ### end Alembic commands ###
